apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: discord-bot-secret # DopplerSecret Name
  namespace: doppler-operator-system
spec:
  tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
    name: doppler-token-discord-bot-prod
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: discordbot-env
    namespace: discordbot # Should match the namespace of deployments that will use the secret
    type: Opaque # Optional: defaults to `Opaque` so can be left out unless changed
